import {
  Users,
  Package,
  QrCode,
  Truck,
  Settings,
  LayoutDashboard,
  Boxes,
  Gift,
  Home,
  ScanLine,
  History,
  Coins,
  Store,
  User,
  LifeBuoy,
  Info,
  LogOut,
  Download,
  Share,
  SquarePlus,
  CircleCheck,
  CircleAlert,
  TriangleAlert,
  X,
  Menu,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  MoreHorizontal,
  Plus,
  Pencil,
  Trash2,
  Eye,
  Search,
  Inbox,
  FileText,
  KeyRound,
  Camera,
  Undo2,
  type LucideIcon,
} from "lucide-react";

/**
 * Single icon surface for the app. Nav configs (server-side) reference icons
 * by string key; client components resolve them through this map — component
 * functions can't cross the server→client boundary.
 */
export const ICONS = {
  users: Users,
  package: Package,
  "qr-code": QrCode,
  truck: Truck,
  settings: Settings,
  dashboard: LayoutDashboard,
  boxes: Boxes,
  gift: Gift,
  home: Home,
  scan: ScanLine,
  history: History,
  coins: Coins,
  store: Store,
  user: User,
  help: LifeBuoy,
  info: Info,
  "log-out": LogOut,
  download: Download,
  share: Share,
  "square-plus": SquarePlus,
  "circle-check": CircleCheck,
  "circle-alert": CircleAlert,
  "triangle-alert": TriangleAlert,
  close: X,
  menu: Menu,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  more: MoreHorizontal,
  plus: Plus,
  pencil: Pencil,
  trash: Trash2,
  eye: Eye,
  search: Search,
  inbox: Inbox,
  "file-text": FileText,
  key: KeyRound,
  camera: Camera,
  undo: Undo2,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
export type { LucideIcon };
